### ISSUE TITLE
Post multiple Media and private Images

### ISSUE THREAD

**Issue by lukadriel7** [laravel-notification-channels/facebook-poster#38]
Hello, I just started using this great package. I have two questions about it. 

It doesn't seem to be possible to upload multiple media at the moment, Is there any plan for that feature ?

The current way of uploading seems to require the file to be a public url. I may be mistaken but trying to upload an image located on my server but not in the public folder resulted in an error. Is it a mistake on my side ? 

Thanks for the package and Happy new year to you all.

**Comment by ahmedash95** [comment]
Hello @lukadriel7, thanks for your nice feedback. 

> It doesn't seem to be possible to upload multiple media at the moment, Is there any plan for that feature?

currently, I can't confirm but I will try to focus on continue supporting this package and make new features. so stay tuned and feel free to create a PR of the feature if you want

> The current way of uploading seems to require the file to be a public URL. I may be mistaken but trying to upload an image located on my server but not in the public folder resulted in an error. Is it a mistake on my side ?

it has been a while since I worked on this package. as far as I remember facebook has to get a valid URL of the image. so there is no way to pass the path of the media instead of a public URL. I'll check FB api and see how possible is it to happen and support private.
